ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "shippingCost" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shippingVatRate" DECIMAL(5,2) NOT NULL DEFAULT 22,
  ADD COLUMN IF NOT EXISTS "shippingVatAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
